#!/usr/bin/env bash
# Run DB Audit Cloud command as a daemon
#
##

PIDFILE="/var/run/dbauditcloud.pid"
LOCKFILE="/var/lock/subsys/dbauditcloud"
RETVAL_SUCCESS=0

usage="Usage: dbauditcloud-daemon (start|stop)"
if [ $# -ne 1 ]; then
	echo $usage
	exit 1
fi

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`

startStop=$1
shift
command=$1
shift
case $startStop in

	(start)

	    if [ -f $PIDFILE ]; then
	      if kill -0 `cat $PIDFILE` > /dev/null 2>&1; then
		echo $command running as process `cat $PIDFILE`.  Stop it first.
		exit 1
	      fi
	    fi
	     KERN=`insmod $bin/../kernel/dbaudit.ko &> $bin/../logs/insmod.log`
	     chardev=`cat /var/log/messages |grep reg | grep -o 'major=[0-9]*' | grep -o '[0-9]*' | tail -n1`
	     NODE=`mknod /dev/dbauditcloud c $chardev 0 &> $bin/../logs/mknod.log`
     	     PROG=`cd $bin;nohup ./CloudCapture &> /dev/null &`
	     ps -fe | grep ./CloudCapture | head -n1 | cut -d" " -f 6 > $PIDFILE
	     RETVAL=$?
	     if [ $RETVAL -ne $RETVAL_SUCCESS ]; then
			rmmod dbaudit
			rm /dev/dbauditcloud
			exit 2
	     fi
	    ;;
	(stop)

	    if [ -f $PIDFILE ]; then
	      if kill -0 `cat $PIDFILE` > /dev/null 2>&1; then
		echo stopping $command
		kill `cat $PIDFILE`
		rmmod dbaudit
	        rm /dev/dbauditcloud
	      else
		echo DB Audit Cloud not running
	      fi
	    else
	      echo DB Audit Cloud not running
	    fi
	    ;;


	(*)
	   echo $usage
	   exit 1
	   ;;
esac
