#!/usr/bin/env bash
# Run odap command as a daemon
#
##

PIDFILE="/var/run/odap.pid"
LOCKFILE="/var/lock/subsys/odap"
RETVAL_SUCCESS=0

usage="Usage: odap-daemon (start|stop)"
if [ $# -ne 1 ]; then
	echo $usage
	exit 1
fi

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`

startStop=$1
shift
command=$1
shift
case $startStop in

	(start)

	    if [ -f $PIDFILE ]; then
	      if kill -0 `cat $PIDFILE` > /dev/null 2>&1; then
		echo $command running as process `cat $PIDFILE`.  Stop it first.
		exit 1
	      fi
	    fi
     	     PROG=`cd $bin;nohup ./odap &> /dev/null &`
	     ps -fe | grep ./odap | head -n1 | cut -d" " -f 6 > $PIDFILE
	     RETVAL=$?
	     if [ $RETVAL -ne $RETVAL_SUCCESS ]; then
			rmmod dbaudit
			rm /dev/odap
			exit 2
	     fi
	    ;;
	(stop)

	    if [ -f $PIDFILE ]; then
	      if kill -0 `cat $PIDFILE` > /dev/null 2>&1; then
		echo stopping $command
		kill `cat $PIDFILE`
		rmmod odap_monitor &> /dev/null
	      else
		echo odap not running
	      fi
	    else
	      echo odap not running
	    fi
	    ;;


	(*)
	   echo $usage
	   exit 1
	   ;;
esac
