/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef auditevent_CONSTANTS_H
#define auditevent_CONSTANTS_H

#include "auditevent_types.h"



class auditeventConstants {
 public:
  auditeventConstants();

};

extern const auditeventConstants g_auditevent_constants;



#endif
