Document: odap-client
Title: Debian odap-client Manual
Author: <insert document author here>
Abstract: This manual describes what odap-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/odap-client/odap-client.sgml.gz

Format: postscript
Files: /usr/share/doc/odap-client/odap-client.ps.gz

Format: text
Files: /usr/share/doc/odap-client/odap-client.text.gz

Format: HTML
Index: /usr/share/doc/odap-client/html/index.html
Files: /usr/share/doc/odap-client/html/*.html
